### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by daemonX10**
docs : Correct the Grammar of CONTRIBUTING.md #11

what does PR do ?
fixed issue : #11 

**Changes Made in this Pull Request**

- Corrected grammar and punctuation errors throughout the `CONTRIBUTING.md` file for improved readability and clarity.

- Enhanced the `.env` section to provide clearer instructions for configuring environment variables. The updated section now includes a sub-heading, code block formatting for environment variables, and explicit instructions on copying the `.env.example` file to `.env.local` and customizing the environment variables.

[video link ](https://www.loom.com/share/7121b402a8e34d7db6b1205d66b03c54)

### CODE REVIEW

**Comment by MrLEGENDx10** [comment]
what does PR do ?
fixed issue : #11 

Update CONTRIBUTING.md  

**Changes Made in this Pull Request**

- Corrected grammar and punctuation errors throughout the `CONTRIBUTING.md` file for improved readability and clarity.

- Enhanced the `.env` section to provide clearer instructions for configuring environment variables. The updated section now includes a sub-heading, code block formatting for environment variables, and explicit instructions on copying the `.env.example` file to `.env.local` and customizing the environment variables.

[video link ](https://www.loom.com/share/7121b402a8e34d7db6b1205d66b03c54)

**Comment by MrLEGENDx10** [comment]
- docs : Correct the Grammar of CONTRIBUTING.md #11

what does PR do ?
fixed issue : #11 

Update CONTRIBUTING.md  

**Changes Made in this Pull Request**

- Corrected grammar and punctuation errors throughout the `CONTRIBUTING.md` file for improved readability and clarity.

- Enhanced the `.env` section to provide clearer instructions for configuring environment variables. The updated section now includes a sub-heading, code block formatting for environment variables, and explicit instructions on copying the `.env.example` file to `.env.local` and customizing the environment variables.

[video link ](https://www.loom.com/share/7121b402a8e34d7db6b1205d66b03c54)

**Comment by piyushgarg-dev** [comment]
Great Work 🎉

**Comment by MrLEGENDx10** [comment]
> Great Work 🎉

Thanks , i'm here after watching your old playlist of opensource . So thank you again .

**Pull request merged**
